/*
 * chmod 모드 0000-7777 의 심볼릭 표기 4096개.
 *
 * **테스트 전용이다.** src/tools/chmod/logic.ts 는 이 표를 참조하지 않고 규칙으로
 * 직접 계산한다. 구현이 이 표를 그대로 읽으면 테스트가 상수 대 상수 비교가 되어
 * 아무것도 검증하지 못한다 — 이 저장소가 열 번 겪은 실수다.
 *
 * 값은 내가 지어낸 것이 아니라 실제 파일에 chmod 를 걸고 stat(1) 의 %Sp 로 읽은
 * 것이다. 생성 방법과 근거는 tools/chmod-vectors/README.md 에 있다.
 */

/** 모드 하나당 9글자씩 이어붙였다. 인덱스는 mode * 9 이다. */
const TABLE =
  '-----------------x-------w--------wx------r--------r-x------rw-------rwx-----x--------x--x-----x' +
  '-w------x-wx-----xr-------xr-x-----xrw------xrwx----w--------w---x----w--w-----w--wx----w-r-----' +
  '-w-r-x----w-rw-----w-rwx----wx-------wx--x----wx-w-----wx-wx----wxr------wxr-x----wxrw-----wxrwx' +
  '---r--------r----x---r---w----r---wx---r--r-----r--r-x---r--rw----r--rwx---r-x------r-x--x---r-x' +
  '-w----r-x-wx---r-xr-----r-xr-x---r-xrw----r-xrwx---rw-------rw---x---rw--w----rw--wx---rw-r-----' +
  'rw-r-x---rw-rw----rw-rwx---rwx------rwx--x---rwx-w----rwx-wx---rwxr-----rwxr-x---rwxrw----rwxrwx' +
  '--x--------x-----x--x----w---x----wx--x---r----x---r-x--x---rw---x---rwx--x--x-----x--x--x--x--x' +
  '-w---x--x-wx--x--xr----x--xr-x--x--xrw---x--xrwx--x-w------x-w---x--x-w--w---x-w--wx--x-w-r----x' +
  '-w-r-x--x-w-rw---x-w-rwx--x-wx-----x-wx--x--x-wx-w---x-wx-wx--x-wxr----x-wxr-x--x-wxrw---x-wxrwx' +
  '--xr-------xr----x--xr---w---xr---wx--xr--r----xr--r-x--xr--rw---xr--rwx--xr-x-----xr-x--x--xr-x' +
  '-w---xr-x-wx--xr-xr----xr-xr-x--xr-xrw---xr-xrwx--xrw------xrw---x--xrw--w---xrw--wx--xrw-r----x' +
  'rw-r-x--xrw-rw---xrw-rwx--xrwx-----xrwx--x--xrwx-w---xrwx-wx--xrwxr----xrwxr-x--xrwxrw---xrwxrwx' +
  '-w--------w------x-w-----w--w-----wx-w----r---w----r-x-w----rw--w----rwx-w---x----w---x--x-w---x' +
  '-w--w---x-wx-w---xr---w---xr-x-w---xrw--w---xrwx-w--w-----w--w---x-w--w--w--w--w--wx-w--w-r---w-' +
  '-w-r-x-w--w-rw--w--w-rwx-w--wx----w--wx--x-w--wx-w--w--wx-wx-w--wxr---w--wxr-x-w--wxrw--w--wxrwx' +
  '-w-r------w-r----x-w-r---w--w-r---wx-w-r--r---w-r--r-x-w-r--rw--w-r--rwx-w-r-x----w-r-x--x-w-r-x' +
  '-w--w-r-x-wx-w-r-xr---w-r-xr-x-w-r-xrw--w-r-xrwx-w-rw-----w-rw---x-w-rw--w--w-rw--wx-w-rw-r---w-' +
  'rw-r-x-w-rw-rw--w-rw-rwx-w-rwx----w-rwx--x-w-rwx-w--w-rwx-wx-w-rwxr---w-rwxr-x-w-rwxrw--w-rwxrwx' +
  '-wx-------wx-----x-wx----w--wx----wx-wx---r---wx---r-x-wx---rw--wx---rwx-wx--x----wx--x--x-wx--x' +
  '-w--wx--x-wx-wx--xr---wx--xr-x-wx--xrw--wx--xrwx-wx-w-----wx-w---x-wx-w--w--wx-w--wx-wx-w-r---wx' +
  '-w-r-x-wx-w-rw--wx-w-rwx-wx-wx----wx-wx--x-wx-wx-w--wx-wx-wx-wx-wxr---wx-wxr-x-wx-wxrw--wx-wxrwx' +
  '-wxr------wxr----x-wxr---w--wxr---wx-wxr--r---wxr--r-x-wxr--rw--wxr--rwx-wxr-x----wxr-x--x-wxr-x' +
  '-w--wxr-x-wx-wxr-xr---wxr-xr-x-wxr-xrw--wxr-xrwx-wxrw-----wxrw---x-wxrw--w--wxrw--wx-wxrw-r---wx' +
  'rw-r-x-wxrw-rw--wxrw-rwx-wxrwx----wxrwx--x-wxrwx-w--wxrwx-wx-wxrwxr---wxrwxr-x-wxrwxrw--wxrwxrwx' +
  'r--------r-------xr------w-r------wxr-----r--r-----r-xr-----rw-r-----rwxr----x---r----x--xr----x' +
  '-w-r----x-wxr----xr--r----xr-xr----xrw-r----xrwxr---w----r---w---xr---w--w-r---w--wxr---w-r--r--' +
  '-w-r-xr---w-rw-r---w-rwxr---wx---r---wx--xr---wx-w-r---wx-wxr---wxr--r---wxr-xr---wxrw-r---wxrwx' +
  'r--r-----r--r----xr--r---w-r--r---wxr--r--r--r--r--r-xr--r--rw-r--r--rwxr--r-x---r--r-x--xr--r-x' +
  '-w-r--r-x-wxr--r-xr--r--r-xr-xr--r-xrw-r--r-xrwxr--rw----r--rw---xr--rw--w-r--rw--wxr--rw-r--r--' +
  'rw-r-xr--rw-rw-r--rw-rwxr--rwx---r--rwx--xr--rwx-w-r--rwx-wxr--rwxr--r--rwxr-xr--rwxrw-r--rwxrwx' +
  'r-x------r-x-----xr-x----w-r-x----wxr-x---r--r-x---r-xr-x---rw-r-x---rwxr-x--x---r-x--x--xr-x--x' +
  '-w-r-x--x-wxr-x--xr--r-x--xr-xr-x--xrw-r-x--xrwxr-x-w----r-x-w---xr-x-w--w-r-x-w--wxr-x-w-r--r-x' +
  '-w-r-xr-x-w-rw-r-x-w-rwxr-x-wx---r-x-wx--xr-x-wx-w-r-x-wx-wxr-x-wxr--r-x-wxr-xr-x-wxrw-r-x-wxrwx' +
  'r-xr-----r-xr----xr-xr---w-r-xr---wxr-xr--r--r-xr--r-xr-xr--rw-r-xr--rwxr-xr-x---r-xr-x--xr-xr-x' +
  '-w-r-xr-x-wxr-xr-xr--r-xr-xr-xr-xr-xrw-r-xr-xrwxr-xrw----r-xrw---xr-xrw--w-r-xrw--wxr-xrw-r--r-x' +
  'rw-r-xr-xrw-rw-r-xrw-rwxr-xrwx---r-xrwx--xr-xrwx-w-r-xrwx-wxr-xrwxr--r-xrwxr-xr-xrwxrw-r-xrwxrwx' +
  'rw-------rw------xrw-----w-rw-----wxrw----r--rw----r-xrw----rw-rw----rwxrw---x---rw---x--xrw---x' +
  '-w-rw---x-wxrw---xr--rw---xr-xrw---xrw-rw---xrwxrw--w----rw--w---xrw--w--w-rw--w--wxrw--w-r--rw-' +
  '-w-r-xrw--w-rw-rw--w-rwxrw--wx---rw--wx--xrw--wx-w-rw--wx-wxrw--wxr--rw--wxr-xrw--wxrw-rw--wxrwx' +
  'rw-r-----rw-r----xrw-r---w-rw-r---wxrw-r--r--rw-r--r-xrw-r--rw-rw-r--rwxrw-r-x---rw-r-x--xrw-r-x' +
  '-w-rw-r-x-wxrw-r-xr--rw-r-xr-xrw-r-xrw-rw-r-xrwxrw-rw----rw-rw---xrw-rw--w-rw-rw--wxrw-rw-r--rw-' +
  'rw-r-xrw-rw-rw-rw-rw-rwxrw-rwx---rw-rwx--xrw-rwx-w-rw-rwx-wxrw-rwxr--rw-rwxr-xrw-rwxrw-rw-rwxrwx' +
  'rwx------rwx-----xrwx----w-rwx----wxrwx---r--rwx---r-xrwx---rw-rwx---rwxrwx--x---rwx--x--xrwx--x' +
  '-w-rwx--x-wxrwx--xr--rwx--xr-xrwx--xrw-rwx--xrwxrwx-w----rwx-w---xrwx-w--w-rwx-w--wxrwx-w-r--rwx' +
  '-w-r-xrwx-w-rw-rwx-w-rwxrwx-wx---rwx-wx--xrwx-wx-w-rwx-wx-wxrwx-wxr--rwx-wxr-xrwx-wxrw-rwx-wxrwx' +
  'rwxr-----rwxr----xrwxr---w-rwxr---wxrwxr--r--rwxr--r-xrwxr--rw-rwxr--rwxrwxr-x---rwxr-x--xrwxr-x' +
  '-w-rwxr-x-wxrwxr-xr--rwxr-xr-xrwxr-xrw-rwxr-xrwxrwxrw----rwxrw---xrwxrw--w-rwxrw--wxrwxrw-r--rwx' +
  'rw-r-xrwxrw-rw-rwxrw-rwxrwxrwx---rwxrwx--xrwxrwx-w-rwxrwx-wxrwxrwxr--rwxrwxr-xrwxrwxrw-rwxrwxrwx' +
  '--------T--------t-------wT-------wt------r-T------r-t------rwT------rwt-----x--T-----x--t-----x' +
  '-wT-----x-wt-----xr-T-----xr-t-----xrwT-----xrwt----w---T----w---t----w--wT----w--wt----w-r-T---' +
  '-w-r-t----w-rwT----w-rwt----wx--T----wx--t----wx-wT----wx-wt----wxr-T----wxr-t----wxrwT----wxrwt' +
  '---r----T---r----t---r---wT---r---wt---r--r-T---r--r-t---r--rwT---r--rwt---r-x--T---r-x--t---r-x' +
  '-wT---r-x-wt---r-xr-T---r-xr-t---r-xrwT---r-xrwt---rw---T---rw---t---rw--wT---rw--wt---rw-r-T---' +
  'rw-r-t---rw-rwT---rw-rwt---rwx--T---rwx--t---rwx-wT---rwx-wt---rwxr-T---rwxr-t---rwxrwT---rwxrwt' +
  '--x-----T--x-----t--x----wT--x----wt--x---r-T--x---r-t--x---rwT--x---rwt--x--x--T--x--x--t--x--x' +
  '-wT--x--x-wt--x--xr-T--x--xr-t--x--xrwT--x--xrwt--x-w---T--x-w---t--x-w--wT--x-w--wt--x-w-r-T--x' +
  '-w-r-t--x-w-rwT--x-w-rwt--x-wx--T--x-wx--t--x-wx-wT--x-wx-wt--x-wxr-T--x-wxr-t--x-wxrwT--x-wxrwt' +
  '--xr----T--xr----t--xr---wT--xr---wt--xr--r-T--xr--r-t--xr--rwT--xr--rwt--xr-x--T--xr-x--t--xr-x' +
  '-wT--xr-x-wt--xr-xr-T--xr-xr-t--xr-xrwT--xr-xrwt--xrw---T--xrw---t--xrw--wT--xrw--wt--xrw-r-T--x' +
  'rw-r-t--xrw-rwT--xrw-rwt--xrwx--T--xrwx--t--xrwx-wT--xrwx-wt--xrwxr-T--xrwxr-t--xrwxrwT--xrwxrwt' +
  '-w------T-w------t-w-----wT-w-----wt-w----r-T-w----r-t-w----rwT-w----rwt-w---x--T-w---x--t-w---x' +
  '-wT-w---x-wt-w---xr-T-w---xr-t-w---xrwT-w---xrwt-w--w---T-w--w---t-w--w--wT-w--w--wt-w--w-r-T-w-' +
  '-w-r-t-w--w-rwT-w--w-rwt-w--wx--T-w--wx--t-w--wx-wT-w--wx-wt-w--wxr-T-w--wxr-t-w--wxrwT-w--wxrwt' +
  '-w-r----T-w-r----t-w-r---wT-w-r---wt-w-r--r-T-w-r--r-t-w-r--rwT-w-r--rwt-w-r-x--T-w-r-x--t-w-r-x' +
  '-wT-w-r-x-wt-w-r-xr-T-w-r-xr-t-w-r-xrwT-w-r-xrwt-w-rw---T-w-rw---t-w-rw--wT-w-rw--wt-w-rw-r-T-w-' +
  'rw-r-t-w-rw-rwT-w-rw-rwt-w-rwx--T-w-rwx--t-w-rwx-wT-w-rwx-wt-w-rwxr-T-w-rwxr-t-w-rwxrwT-w-rwxrwt' +
  '-wx-----T-wx-----t-wx----wT-wx----wt-wx---r-T-wx---r-t-wx---rwT-wx---rwt-wx--x--T-wx--x--t-wx--x' +
  '-wT-wx--x-wt-wx--xr-T-wx--xr-t-wx--xrwT-wx--xrwt-wx-w---T-wx-w---t-wx-w--wT-wx-w--wt-wx-w-r-T-wx' +
  '-w-r-t-wx-w-rwT-wx-w-rwt-wx-wx--T-wx-wx--t-wx-wx-wT-wx-wx-wt-wx-wxr-T-wx-wxr-t-wx-wxrwT-wx-wxrwt' +
  '-wxr----T-wxr----t-wxr---wT-wxr---wt-wxr--r-T-wxr--r-t-wxr--rwT-wxr--rwt-wxr-x--T-wxr-x--t-wxr-x' +
  '-wT-wxr-x-wt-wxr-xr-T-wxr-xr-t-wxr-xrwT-wxr-xrwt-wxrw---T-wxrw---t-wxrw--wT-wxrw--wt-wxrw-r-T-wx' +
  'rw-r-t-wxrw-rwT-wxrw-rwt-wxrwx--T-wxrwx--t-wxrwx-wT-wxrwx-wt-wxrwxr-T-wxrwxr-t-wxrwxrwT-wxrwxrwt' +
  'r-------Tr-------tr------wTr------wtr-----r-Tr-----r-tr-----rwTr-----rwtr----x--Tr----x--tr----x' +
  '-wTr----x-wtr----xr-Tr----xr-tr----xrwTr----xrwtr---w---Tr---w---tr---w--wTr---w--wtr---w-r-Tr--' +
  '-w-r-tr---w-rwTr---w-rwtr---wx--Tr---wx--tr---wx-wTr---wx-wtr---wxr-Tr---wxr-tr---wxrwTr---wxrwt' +
  'r--r----Tr--r----tr--r---wTr--r---wtr--r--r-Tr--r--r-tr--r--rwTr--r--rwtr--r-x--Tr--r-x--tr--r-x' +
  '-wTr--r-x-wtr--r-xr-Tr--r-xr-tr--r-xrwTr--r-xrwtr--rw---Tr--rw---tr--rw--wTr--rw--wtr--rw-r-Tr--' +
  'rw-r-tr--rw-rwTr--rw-rwtr--rwx--Tr--rwx--tr--rwx-wTr--rwx-wtr--rwxr-Tr--rwxr-tr--rwxrwTr--rwxrwt' +
  'r-x-----Tr-x-----tr-x----wTr-x----wtr-x---r-Tr-x---r-tr-x---rwTr-x---rwtr-x--x--Tr-x--x--tr-x--x' +
  '-wTr-x--x-wtr-x--xr-Tr-x--xr-tr-x--xrwTr-x--xrwtr-x-w---Tr-x-w---tr-x-w--wTr-x-w--wtr-x-w-r-Tr-x' +
  '-w-r-tr-x-w-rwTr-x-w-rwtr-x-wx--Tr-x-wx--tr-x-wx-wTr-x-wx-wtr-x-wxr-Tr-x-wxr-tr-x-wxrwTr-x-wxrwt' +
  'r-xr----Tr-xr----tr-xr---wTr-xr---wtr-xr--r-Tr-xr--r-tr-xr--rwTr-xr--rwtr-xr-x--Tr-xr-x--tr-xr-x' +
  '-wTr-xr-x-wtr-xr-xr-Tr-xr-xr-tr-xr-xrwTr-xr-xrwtr-xrw---Tr-xrw---tr-xrw--wTr-xrw--wtr-xrw-r-Tr-x' +
  'rw-r-tr-xrw-rwTr-xrw-rwtr-xrwx--Tr-xrwx--tr-xrwx-wTr-xrwx-wtr-xrwxr-Tr-xrwxr-tr-xrwxrwTr-xrwxrwt' +
  'rw------Trw------trw-----wTrw-----wtrw----r-Trw----r-trw----rwTrw----rwtrw---x--Trw---x--trw---x' +
  '-wTrw---x-wtrw---xr-Trw---xr-trw---xrwTrw---xrwtrw--w---Trw--w---trw--w--wTrw--w--wtrw--w-r-Trw-' +
  '-w-r-trw--w-rwTrw--w-rwtrw--wx--Trw--wx--trw--wx-wTrw--wx-wtrw--wxr-Trw--wxr-trw--wxrwTrw--wxrwt' +
  'rw-r----Trw-r----trw-r---wTrw-r---wtrw-r--r-Trw-r--r-trw-r--rwTrw-r--rwtrw-r-x--Trw-r-x--trw-r-x' +
  '-wTrw-r-x-wtrw-r-xr-Trw-r-xr-trw-r-xrwTrw-r-xrwtrw-rw---Trw-rw---trw-rw--wTrw-rw--wtrw-rw-r-Trw-' +
  'rw-r-trw-rw-rwTrw-rw-rwtrw-rwx--Trw-rwx--trw-rwx-wTrw-rwx-wtrw-rwxr-Trw-rwxr-trw-rwxrwTrw-rwxrwt' +
  'rwx-----Trwx-----trwx----wTrwx----wtrwx---r-Trwx---r-trwx---rwTrwx---rwtrwx--x--Trwx--x--trwx--x' +
  '-wTrwx--x-wtrwx--xr-Trwx--xr-trwx--xrwTrwx--xrwtrwx-w---Trwx-w---trwx-w--wTrwx-w--wtrwx-w-r-Trwx' +
  '-w-r-trwx-w-rwTrwx-w-rwtrwx-wx--Trwx-wx--trwx-wx-wTrwx-wx-wtrwx-wxr-Trwx-wxr-trwx-wxrwTrwx-wxrwt' +
  'rwxr----Trwxr----trwxr---wTrwxr---wtrwxr--r-Trwxr--r-trwxr--rwTrwxr--rwtrwxr-x--Trwxr-x--trwxr-x' +
  '-wTrwxr-x-wtrwxr-xr-Trwxr-xr-trwxr-xrwTrwxr-xrwtrwxrw---Trwxrw---trwxrw--wTrwxrw--wtrwxrw-r-Trwx' +
  'rw-r-trwxrw-rwTrwxrw-rwtrwxrwx--Trwxrwx--trwxrwx-wTrwxrwx-wtrwxrwxr-Trwxrwxr-trwxrwxrwTrwxrwxrwt' +
  '-----S--------S--x-----S-w------S-wx-----Sr-------Sr-x-----Srw------Srwx-----s--------s--x-----s' +
  '-w------s-wx-----sr-------sr-x-----srw------srwx----wS-------wS--x----wS-w-----wS-wx----wSr-----' +
  '-wSr-x----wSrw-----wSrwx----ws-------ws--x----ws-w-----ws-wx----wsr------wsr-x----wsrw-----wsrwx' +
  '---r-S------r-S--x---r-S-w----r-S-wx---r-Sr-----r-Sr-x---r-Srw----r-Srwx---r-s------r-s--x---r-s' +
  '-w----r-s-wx---r-sr-----r-sr-x---r-srw----r-srwx---rwS------rwS--x---rwS-w----rwS-wx---rwSr-----' +
  'rwSr-x---rwSrw----rwSrwx---rws------rws--x---rws-w----rws-wx---rwsr-----rwsr-x---rwsrw----rwsrwx' +
  '--x--S-----x--S--x--x--S-w---x--S-wx--x--Sr----x--Sr-x--x--Srw---x--Srwx--x--s-----x--s--x--x--s' +
  '-w---x--s-wx--x--sr----x--sr-x--x--srw---x--srwx--x-wS-----x-wS--x--x-wS-w---x-wS-wx--x-wSr----x' +
  '-wSr-x--x-wSrw---x-wSrwx--x-ws-----x-ws--x--x-ws-w---x-ws-wx--x-wsr----x-wsr-x--x-wsrw---x-wsrwx' +
  '--xr-S-----xr-S--x--xr-S-w---xr-S-wx--xr-Sr----xr-Sr-x--xr-Srw---xr-Srwx--xr-s-----xr-s--x--xr-s' +
  '-w---xr-s-wx--xr-sr----xr-sr-x--xr-srw---xr-srwx--xrwS-----xrwS--x--xrwS-w---xrwS-wx--xrwSr----x' +
  'rwSr-x--xrwSrw---xrwSrwx--xrws-----xrws--x--xrws-w---xrws-wx--xrwsr----xrwsr-x--xrwsrw---xrwsrwx' +
  '-w---S----w---S--x-w---S-w--w---S-wx-w---Sr---w---Sr-x-w---Srw--w---Srwx-w---s----w---s--x-w---s' +
  '-w--w---s-wx-w---sr---w---sr-x-w---srw--w---srwx-w--wS----w--wS--x-w--wS-w--w--wS-wx-w--wSr---w-' +
  '-wSr-x-w--wSrw--w--wSrwx-w--ws----w--ws--x-w--ws-w--w--ws-wx-w--wsr---w--wsr-x-w--wsrw--w--wsrwx' +
  '-w-r-S----w-r-S--x-w-r-S-w--w-r-S-wx-w-r-Sr---w-r-Sr-x-w-r-Srw--w-r-Srwx-w-r-s----w-r-s--x-w-r-s' +
  '-w--w-r-s-wx-w-r-sr---w-r-sr-x-w-r-srw--w-r-srwx-w-rwS----w-rwS--x-w-rwS-w--w-rwS-wx-w-rwSr---w-' +
  'rwSr-x-w-rwSrw--w-rwSrwx-w-rws----w-rws--x-w-rws-w--w-rws-wx-w-rwsr---w-rwsr-x-w-rwsrw--w-rwsrwx' +
  '-wx--S----wx--S--x-wx--S-w--wx--S-wx-wx--Sr---wx--Sr-x-wx--Srw--wx--Srwx-wx--s----wx--s--x-wx--s' +
  '-w--wx--s-wx-wx--sr---wx--sr-x-wx--srw--wx--srwx-wx-wS----wx-wS--x-wx-wS-w--wx-wS-wx-wx-wSr---wx' +
  '-wSr-x-wx-wSrw--wx-wSrwx-wx-ws----wx-ws--x-wx-ws-w--wx-ws-wx-wx-wsr---wx-wsr-x-wx-wsrw--wx-wsrwx' +
  '-wxr-S----wxr-S--x-wxr-S-w--wxr-S-wx-wxr-Sr---wxr-Sr-x-wxr-Srw--wxr-Srwx-wxr-s----wxr-s--x-wxr-s' +
  '-w--wxr-s-wx-wxr-sr---wxr-sr-x-wxr-srw--wxr-srwx-wxrwS----wxrwS--x-wxrwS-w--wxrwS-wx-wxrwSr---wx' +
  'rwSr-x-wxrwSrw--wxrwSrwx-wxrws----wxrws--x-wxrws-w--wxrws-wx-wxrwsr---wxrwsr-x-wxrwsrw--wxrwsrwx' +
  'r----S---r----S--xr----S-w-r----S-wxr----Sr--r----Sr-xr----Srw-r----Srwxr----s---r----s--xr----s' +
  '-w-r----s-wxr----sr--r----sr-xr----srw-r----srwxr---wS---r---wS--xr---wS-w-r---wS-wxr---wSr--r--' +
  '-wSr-xr---wSrw-r---wSrwxr---ws---r---ws--xr---ws-w-r---ws-wxr---wsr--r---wsr-xr---wsrw-r---wsrwx' +
  'r--r-S---r--r-S--xr--r-S-w-r--r-S-wxr--r-Sr--r--r-Sr-xr--r-Srw-r--r-Srwxr--r-s---r--r-s--xr--r-s' +
  '-w-r--r-s-wxr--r-sr--r--r-sr-xr--r-srw-r--r-srwxr--rwS---r--rwS--xr--rwS-w-r--rwS-wxr--rwSr--r--' +
  'rwSr-xr--rwSrw-r--rwSrwxr--rws---r--rws--xr--rws-w-r--rws-wxr--rwsr--r--rwsr-xr--rwsrw-r--rwsrwx' +
  'r-x--S---r-x--S--xr-x--S-w-r-x--S-wxr-x--Sr--r-x--Sr-xr-x--Srw-r-x--Srwxr-x--s---r-x--s--xr-x--s' +
  '-w-r-x--s-wxr-x--sr--r-x--sr-xr-x--srw-r-x--srwxr-x-wS---r-x-wS--xr-x-wS-w-r-x-wS-wxr-x-wSr--r-x' +
  '-wSr-xr-x-wSrw-r-x-wSrwxr-x-ws---r-x-ws--xr-x-ws-w-r-x-ws-wxr-x-wsr--r-x-wsr-xr-x-wsrw-r-x-wsrwx' +
  'r-xr-S---r-xr-S--xr-xr-S-w-r-xr-S-wxr-xr-Sr--r-xr-Sr-xr-xr-Srw-r-xr-Srwxr-xr-s---r-xr-s--xr-xr-s' +
  '-w-r-xr-s-wxr-xr-sr--r-xr-sr-xr-xr-srw-r-xr-srwxr-xrwS---r-xrwS--xr-xrwS-w-r-xrwS-wxr-xrwSr--r-x' +
  'rwSr-xr-xrwSrw-r-xrwSrwxr-xrws---r-xrws--xr-xrws-w-r-xrws-wxr-xrwsr--r-xrwsr-xr-xrwsrw-r-xrwsrwx' +
  'rw---S---rw---S--xrw---S-w-rw---S-wxrw---Sr--rw---Sr-xrw---Srw-rw---Srwxrw---s---rw---s--xrw---s' +
  '-w-rw---s-wxrw---sr--rw---sr-xrw---srw-rw---srwxrw--wS---rw--wS--xrw--wS-w-rw--wS-wxrw--wSr--rw-' +
  '-wSr-xrw--wSrw-rw--wSrwxrw--ws---rw--ws--xrw--ws-w-rw--ws-wxrw--wsr--rw--wsr-xrw--wsrw-rw--wsrwx' +
  'rw-r-S---rw-r-S--xrw-r-S-w-rw-r-S-wxrw-r-Sr--rw-r-Sr-xrw-r-Srw-rw-r-Srwxrw-r-s---rw-r-s--xrw-r-s' +
  '-w-rw-r-s-wxrw-r-sr--rw-r-sr-xrw-r-srw-rw-r-srwxrw-rwS---rw-rwS--xrw-rwS-w-rw-rwS-wxrw-rwSr--rw-' +
  'rwSr-xrw-rwSrw-rw-rwSrwxrw-rws---rw-rws--xrw-rws-w-rw-rws-wxrw-rwsr--rw-rwsr-xrw-rwsrw-rw-rwsrwx' +
  'rwx--S---rwx--S--xrwx--S-w-rwx--S-wxrwx--Sr--rwx--Sr-xrwx--Srw-rwx--Srwxrwx--s---rwx--s--xrwx--s' +
  '-w-rwx--s-wxrwx--sr--rwx--sr-xrwx--srw-rwx--srwxrwx-wS---rwx-wS--xrwx-wS-w-rwx-wS-wxrwx-wSr--rwx' +
  '-wSr-xrwx-wSrw-rwx-wSrwxrwx-ws---rwx-ws--xrwx-ws-w-rwx-ws-wxrwx-wsr--rwx-wsr-xrwx-wsrw-rwx-wsrwx' +
  'rwxr-S---rwxr-S--xrwxr-S-w-rwxr-S-wxrwxr-Sr--rwxr-Sr-xrwxr-Srw-rwxr-Srwxrwxr-s---rwxr-s--xrwxr-s' +
  '-w-rwxr-s-wxrwxr-sr--rwxr-sr-xrwxr-srw-rwxr-srwxrwxrwS---rwxrwS--xrwxrwS-w-rwxrwS-wxrwxrwSr--rwx' +
  'rwSr-xrwxrwSrw-rwxrwSrwxrwxrws---rwxrws--xrwxrws-w-rwxrws-wxrwxrwsr--rwxrwsr-xrwxrwsrw-rwxrwsrwx' +
  '-----S--T-----S--t-----S-wT-----S-wt-----Sr-T-----Sr-t-----SrwT-----Srwt-----s--T-----s--t-----s' +
  '-wT-----s-wt-----sr-T-----sr-t-----srwT-----srwt----wS--T----wS--t----wS-wT----wS-wt----wSr-T---' +
  '-wSr-t----wSrwT----wSrwt----ws--T----ws--t----ws-wT----ws-wt----wsr-T----wsr-t----wsrwT----wsrwt' +
  '---r-S--T---r-S--t---r-S-wT---r-S-wt---r-Sr-T---r-Sr-t---r-SrwT---r-Srwt---r-s--T---r-s--t---r-s' +
  '-wT---r-s-wt---r-sr-T---r-sr-t---r-srwT---r-srwt---rwS--T---rwS--t---rwS-wT---rwS-wt---rwSr-T---' +
  'rwSr-t---rwSrwT---rwSrwt---rws--T---rws--t---rws-wT---rws-wt---rwsr-T---rwsr-t---rwsrwT---rwsrwt' +
  '--x--S--T--x--S--t--x--S-wT--x--S-wt--x--Sr-T--x--Sr-t--x--SrwT--x--Srwt--x--s--T--x--s--t--x--s' +
  '-wT--x--s-wt--x--sr-T--x--sr-t--x--srwT--x--srwt--x-wS--T--x-wS--t--x-wS-wT--x-wS-wt--x-wSr-T--x' +
  '-wSr-t--x-wSrwT--x-wSrwt--x-ws--T--x-ws--t--x-ws-wT--x-ws-wt--x-wsr-T--x-wsr-t--x-wsrwT--x-wsrwt' +
  '--xr-S--T--xr-S--t--xr-S-wT--xr-S-wt--xr-Sr-T--xr-Sr-t--xr-SrwT--xr-Srwt--xr-s--T--xr-s--t--xr-s' +
  '-wT--xr-s-wt--xr-sr-T--xr-sr-t--xr-srwT--xr-srwt--xrwS--T--xrwS--t--xrwS-wT--xrwS-wt--xrwSr-T--x' +
  'rwSr-t--xrwSrwT--xrwSrwt--xrws--T--xrws--t--xrws-wT--xrws-wt--xrwsr-T--xrwsr-t--xrwsrwT--xrwsrwt' +
  '-w---S--T-w---S--t-w---S-wT-w---S-wt-w---Sr-T-w---Sr-t-w---SrwT-w---Srwt-w---s--T-w---s--t-w---s' +
  '-wT-w---s-wt-w---sr-T-w---sr-t-w---srwT-w---srwt-w--wS--T-w--wS--t-w--wS-wT-w--wS-wt-w--wSr-T-w-' +
  '-wSr-t-w--wSrwT-w--wSrwt-w--ws--T-w--ws--t-w--ws-wT-w--ws-wt-w--wsr-T-w--wsr-t-w--wsrwT-w--wsrwt' +
  '-w-r-S--T-w-r-S--t-w-r-S-wT-w-r-S-wt-w-r-Sr-T-w-r-Sr-t-w-r-SrwT-w-r-Srwt-w-r-s--T-w-r-s--t-w-r-s' +
  '-wT-w-r-s-wt-w-r-sr-T-w-r-sr-t-w-r-srwT-w-r-srwt-w-rwS--T-w-rwS--t-w-rwS-wT-w-rwS-wt-w-rwSr-T-w-' +
  'rwSr-t-w-rwSrwT-w-rwSrwt-w-rws--T-w-rws--t-w-rws-wT-w-rws-wt-w-rwsr-T-w-rwsr-t-w-rwsrwT-w-rwsrwt' +
  '-wx--S--T-wx--S--t-wx--S-wT-wx--S-wt-wx--Sr-T-wx--Sr-t-wx--SrwT-wx--Srwt-wx--s--T-wx--s--t-wx--s' +
  '-wT-wx--s-wt-wx--sr-T-wx--sr-t-wx--srwT-wx--srwt-wx-wS--T-wx-wS--t-wx-wS-wT-wx-wS-wt-wx-wSr-T-wx' +
  '-wSr-t-wx-wSrwT-wx-wSrwt-wx-ws--T-wx-ws--t-wx-ws-wT-wx-ws-wt-wx-wsr-T-wx-wsr-t-wx-wsrwT-wx-wsrwt' +
  '-wxr-S--T-wxr-S--t-wxr-S-wT-wxr-S-wt-wxr-Sr-T-wxr-Sr-t-wxr-SrwT-wxr-Srwt-wxr-s--T-wxr-s--t-wxr-s' +
  '-wT-wxr-s-wt-wxr-sr-T-wxr-sr-t-wxr-srwT-wxr-srwt-wxrwS--T-wxrwS--t-wxrwS-wT-wxrwS-wt-wxrwSr-T-wx' +
  'rwSr-t-wxrwSrwT-wxrwSrwt-wxrws--T-wxrws--t-wxrws-wT-wxrws-wt-wxrwsr-T-wxrwsr-t-wxrwsrwT-wxrwsrwt' +
  'r----S--Tr----S--tr----S-wTr----S-wtr----Sr-Tr----Sr-tr----SrwTr----Srwtr----s--Tr----s--tr----s' +
  '-wTr----s-wtr----sr-Tr----sr-tr----srwTr----srwtr---wS--Tr---wS--tr---wS-wTr---wS-wtr---wSr-Tr--' +
  '-wSr-tr---wSrwTr---wSrwtr---ws--Tr---ws--tr---ws-wTr---ws-wtr---wsr-Tr---wsr-tr---wsrwTr---wsrwt' +
  'r--r-S--Tr--r-S--tr--r-S-wTr--r-S-wtr--r-Sr-Tr--r-Sr-tr--r-SrwTr--r-Srwtr--r-s--Tr--r-s--tr--r-s' +
  '-wTr--r-s-wtr--r-sr-Tr--r-sr-tr--r-srwTr--r-srwtr--rwS--Tr--rwS--tr--rwS-wTr--rwS-wtr--rwSr-Tr--' +
  'rwSr-tr--rwSrwTr--rwSrwtr--rws--Tr--rws--tr--rws-wTr--rws-wtr--rwsr-Tr--rwsr-tr--rwsrwTr--rwsrwt' +
  'r-x--S--Tr-x--S--tr-x--S-wTr-x--S-wtr-x--Sr-Tr-x--Sr-tr-x--SrwTr-x--Srwtr-x--s--Tr-x--s--tr-x--s' +
  '-wTr-x--s-wtr-x--sr-Tr-x--sr-tr-x--srwTr-x--srwtr-x-wS--Tr-x-wS--tr-x-wS-wTr-x-wS-wtr-x-wSr-Tr-x' +
  '-wSr-tr-x-wSrwTr-x-wSrwtr-x-ws--Tr-x-ws--tr-x-ws-wTr-x-ws-wtr-x-wsr-Tr-x-wsr-tr-x-wsrwTr-x-wsrwt' +
  'r-xr-S--Tr-xr-S--tr-xr-S-wTr-xr-S-wtr-xr-Sr-Tr-xr-Sr-tr-xr-SrwTr-xr-Srwtr-xr-s--Tr-xr-s--tr-xr-s' +
  '-wTr-xr-s-wtr-xr-sr-Tr-xr-sr-tr-xr-srwTr-xr-srwtr-xrwS--Tr-xrwS--tr-xrwS-wTr-xrwS-wtr-xrwSr-Tr-x' +
  'rwSr-tr-xrwSrwTr-xrwSrwtr-xrws--Tr-xrws--tr-xrws-wTr-xrws-wtr-xrwsr-Tr-xrwsr-tr-xrwsrwTr-xrwsrwt' +
  'rw---S--Trw---S--trw---S-wTrw---S-wtrw---Sr-Trw---Sr-trw---SrwTrw---Srwtrw---s--Trw---s--trw---s' +
  '-wTrw---s-wtrw---sr-Trw---sr-trw---srwTrw---srwtrw--wS--Trw--wS--trw--wS-wTrw--wS-wtrw--wSr-Trw-' +
  '-wSr-trw--wSrwTrw--wSrwtrw--ws--Trw--ws--trw--ws-wTrw--ws-wtrw--wsr-Trw--wsr-trw--wsrwTrw--wsrwt' +
  'rw-r-S--Trw-r-S--trw-r-S-wTrw-r-S-wtrw-r-Sr-Trw-r-Sr-trw-r-SrwTrw-r-Srwtrw-r-s--Trw-r-s--trw-r-s' +
  '-wTrw-r-s-wtrw-r-sr-Trw-r-sr-trw-r-srwTrw-r-srwtrw-rwS--Trw-rwS--trw-rwS-wTrw-rwS-wtrw-rwSr-Trw-' +
  'rwSr-trw-rwSrwTrw-rwSrwtrw-rws--Trw-rws--trw-rws-wTrw-rws-wtrw-rwsr-Trw-rwsr-trw-rwsrwTrw-rwsrwt' +
  'rwx--S--Trwx--S--trwx--S-wTrwx--S-wtrwx--Sr-Trwx--Sr-trwx--SrwTrwx--Srwtrwx--s--Trwx--s--trwx--s' +
  '-wTrwx--s-wtrwx--sr-Trwx--sr-trwx--srwTrwx--srwtrwx-wS--Trwx-wS--trwx-wS-wTrwx-wS-wtrwx-wSr-Trwx' +
  '-wSr-trwx-wSrwTrwx-wSrwtrwx-ws--Trwx-ws--trwx-ws-wTrwx-ws-wtrwx-wsr-Trwx-wsr-trwx-wsrwTrwx-wsrwt' +
  'rwxr-S--Trwxr-S--trwxr-S-wTrwxr-S-wtrwxr-Sr-Trwxr-Sr-trwxr-SrwTrwxr-Srwtrwxr-s--Trwxr-s--trwxr-s' +
  '-wTrwxr-s-wtrwxr-sr-Trwxr-sr-trwxr-srwTrwxr-srwtrwxrwS--TrwxrwS--trwxrwS-wTrwxrwS-wtrwxrwSr-Trwx' +
  'rwSr-trwxrwSrwTrwxrwSrwtrwxrws--Trwxrws--trwxrws-wTrwxrws-wtrwxrwsr-Trwxrwsr-trwxrwsrwTrwxrwsrwt' +
  '--S--------S-----x--S----w---S----wx--S---r----S---r-x--S---rw---S---rwx--S--x-----S--x--x--S--x' +
  '-w---S--x-wx--S--xr----S--xr-x--S--xrw---S--xrwx--S-w------S-w---x--S-w--w---S-w--wx--S-w-r----S' +
  '-w-r-x--S-w-rw---S-w-rwx--S-wx-----S-wx--x--S-wx-w---S-wx-wx--S-wxr----S-wxr-x--S-wxrw---S-wxrwx' +
  '--Sr-------Sr----x--Sr---w---Sr---wx--Sr--r----Sr--r-x--Sr--rw---Sr--rwx--Sr-x-----Sr-x--x--Sr-x' +
  '-w---Sr-x-wx--Sr-xr----Sr-xr-x--Sr-xrw---Sr-xrwx--Srw------Srw---x--Srw--w---Srw--wx--Srw-r----S' +
  'rw-r-x--Srw-rw---Srw-rwx--Srwx-----Srwx--x--Srwx-w---Srwx-wx--Srwxr----Srwxr-x--Srwxrw---Srwxrwx' +
  '--s--------s-----x--s----w---s----wx--s---r----s---r-x--s---rw---s---rwx--s--x-----s--x--x--s--x' +
  '-w---s--x-wx--s--xr----s--xr-x--s--xrw---s--xrwx--s-w------s-w---x--s-w--w---s-w--wx--s-w-r----s' +
  '-w-r-x--s-w-rw---s-w-rwx--s-wx-----s-wx--x--s-wx-w---s-wx-wx--s-wxr----s-wxr-x--s-wxrw---s-wxrwx' +
  '--sr-------sr----x--sr---w---sr---wx--sr--r----sr--r-x--sr--rw---sr--rwx--sr-x-----sr-x--x--sr-x' +
  '-w---sr-x-wx--sr-xr----sr-xr-x--sr-xrw---sr-xrwx--srw------srw---x--srw--w---srw--wx--srw-r----s' +
  'rw-r-x--srw-rw---srw-rwx--srwx-----srwx--x--srwx-w---srwx-wx--srwxr----srwxr-x--srwxrw---srwxrwx' +
  '-wS-------wS-----x-wS----w--wS----wx-wS---r---wS---r-x-wS---rw--wS---rwx-wS--x----wS--x--x-wS--x' +
  '-w--wS--x-wx-wS--xr---wS--xr-x-wS--xrw--wS--xrwx-wS-w-----wS-w---x-wS-w--w--wS-w--wx-wS-w-r---wS' +
  '-w-r-x-wS-w-rw--wS-w-rwx-wS-wx----wS-wx--x-wS-wx-w--wS-wx-wx-wS-wxr---wS-wxr-x-wS-wxrw--wS-wxrwx' +
  '-wSr------wSr----x-wSr---w--wSr---wx-wSr--r---wSr--r-x-wSr--rw--wSr--rwx-wSr-x----wSr-x--x-wSr-x' +
  '-w--wSr-x-wx-wSr-xr---wSr-xr-x-wSr-xrw--wSr-xrwx-wSrw-----wSrw---x-wSrw--w--wSrw--wx-wSrw-r---wS' +
  'rw-r-x-wSrw-rw--wSrw-rwx-wSrwx----wSrwx--x-wSrwx-w--wSrwx-wx-wSrwxr---wSrwxr-x-wSrwxrw--wSrwxrwx' +
  '-ws-------ws-----x-ws----w--ws----wx-ws---r---ws---r-x-ws---rw--ws---rwx-ws--x----ws--x--x-ws--x' +
  '-w--ws--x-wx-ws--xr---ws--xr-x-ws--xrw--ws--xrwx-ws-w-----ws-w---x-ws-w--w--ws-w--wx-ws-w-r---ws' +
  '-w-r-x-ws-w-rw--ws-w-rwx-ws-wx----ws-wx--x-ws-wx-w--ws-wx-wx-ws-wxr---ws-wxr-x-ws-wxrw--ws-wxrwx' +
  '-wsr------wsr----x-wsr---w--wsr---wx-wsr--r---wsr--r-x-wsr--rw--wsr--rwx-wsr-x----wsr-x--x-wsr-x' +
  '-w--wsr-x-wx-wsr-xr---wsr-xr-x-wsr-xrw--wsr-xrwx-wsrw-----wsrw---x-wsrw--w--wsrw--wx-wsrw-r---ws' +
  'rw-r-x-wsrw-rw--wsrw-rwx-wsrwx----wsrwx--x-wsrwx-w--wsrwx-wx-wsrwxr---wsrwxr-x-wsrwxrw--wsrwxrwx' +
  'r-S------r-S-----xr-S----w-r-S----wxr-S---r--r-S---r-xr-S---rw-r-S---rwxr-S--x---r-S--x--xr-S--x' +
  '-w-r-S--x-wxr-S--xr--r-S--xr-xr-S--xrw-r-S--xrwxr-S-w----r-S-w---xr-S-w--w-r-S-w--wxr-S-w-r--r-S' +
  '-w-r-xr-S-w-rw-r-S-w-rwxr-S-wx---r-S-wx--xr-S-wx-w-r-S-wx-wxr-S-wxr--r-S-wxr-xr-S-wxrw-r-S-wxrwx' +
  'r-Sr-----r-Sr----xr-Sr---w-r-Sr---wxr-Sr--r--r-Sr--r-xr-Sr--rw-r-Sr--rwxr-Sr-x---r-Sr-x--xr-Sr-x' +
  '-w-r-Sr-x-wxr-Sr-xr--r-Sr-xr-xr-Sr-xrw-r-Sr-xrwxr-Srw----r-Srw---xr-Srw--w-r-Srw--wxr-Srw-r--r-S' +
  'rw-r-xr-Srw-rw-r-Srw-rwxr-Srwx---r-Srwx--xr-Srwx-w-r-Srwx-wxr-Srwxr--r-Srwxr-xr-Srwxrw-r-Srwxrwx' +
  'r-s------r-s-----xr-s----w-r-s----wxr-s---r--r-s---r-xr-s---rw-r-s---rwxr-s--x---r-s--x--xr-s--x' +
  '-w-r-s--x-wxr-s--xr--r-s--xr-xr-s--xrw-r-s--xrwxr-s-w----r-s-w---xr-s-w--w-r-s-w--wxr-s-w-r--r-s' +
  '-w-r-xr-s-w-rw-r-s-w-rwxr-s-wx---r-s-wx--xr-s-wx-w-r-s-wx-wxr-s-wxr--r-s-wxr-xr-s-wxrw-r-s-wxrwx' +
  'r-sr-----r-sr----xr-sr---w-r-sr---wxr-sr--r--r-sr--r-xr-sr--rw-r-sr--rwxr-sr-x---r-sr-x--xr-sr-x' +
  '-w-r-sr-x-wxr-sr-xr--r-sr-xr-xr-sr-xrw-r-sr-xrwxr-srw----r-srw---xr-srw--w-r-srw--wxr-srw-r--r-s' +
  'rw-r-xr-srw-rw-r-srw-rwxr-srwx---r-srwx--xr-srwx-w-r-srwx-wxr-srwxr--r-srwxr-xr-srwxrw-r-srwxrwx' +
  'rwS------rwS-----xrwS----w-rwS----wxrwS---r--rwS---r-xrwS---rw-rwS---rwxrwS--x---rwS--x--xrwS--x' +
  '-w-rwS--x-wxrwS--xr--rwS--xr-xrwS--xrw-rwS--xrwxrwS-w----rwS-w---xrwS-w--w-rwS-w--wxrwS-w-r--rwS' +
  '-w-r-xrwS-w-rw-rwS-w-rwxrwS-wx---rwS-wx--xrwS-wx-w-rwS-wx-wxrwS-wxr--rwS-wxr-xrwS-wxrw-rwS-wxrwx' +
  'rwSr-----rwSr----xrwSr---w-rwSr---wxrwSr--r--rwSr--r-xrwSr--rw-rwSr--rwxrwSr-x---rwSr-x--xrwSr-x' +
  '-w-rwSr-x-wxrwSr-xr--rwSr-xr-xrwSr-xrw-rwSr-xrwxrwSrw----rwSrw---xrwSrw--w-rwSrw--wxrwSrw-r--rwS' +
  'rw-r-xrwSrw-rw-rwSrw-rwxrwSrwx---rwSrwx--xrwSrwx-w-rwSrwx-wxrwSrwxr--rwSrwxr-xrwSrwxrw-rwSrwxrwx' +
  'rws------rws-----xrws----w-rws----wxrws---r--rws---r-xrws---rw-rws---rwxrws--x---rws--x--xrws--x' +
  '-w-rws--x-wxrws--xr--rws--xr-xrws--xrw-rws--xrwxrws-w----rws-w---xrws-w--w-rws-w--wxrws-w-r--rws' +
  '-w-r-xrws-w-rw-rws-w-rwxrws-wx---rws-wx--xrws-wx-w-rws-wx-wxrws-wxr--rws-wxr-xrws-wxrw-rws-wxrwx' +
  'rwsr-----rwsr----xrwsr---w-rwsr---wxrwsr--r--rwsr--r-xrwsr--rw-rwsr--rwxrwsr-x---rwsr-x--xrwsr-x' +
  '-w-rwsr-x-wxrwsr-xr--rwsr-xr-xrwsr-xrw-rwsr-xrwxrwsrw----rwsrw---xrwsrw--w-rwsrw--wxrwsrw-r--rws' +
  'rw-r-xrwsrw-rw-rwsrw-rwxrwsrwx---rwsrwx--xrwsrwx-w-rwsrwx-wxrwsrwxr--rwsrwxr-xrwsrwxrw-rwsrwxrwx' +
  '--S-----T--S-----t--S----wT--S----wt--S---r-T--S---r-t--S---rwT--S---rwt--S--x--T--S--x--t--S--x' +
  '-wT--S--x-wt--S--xr-T--S--xr-t--S--xrwT--S--xrwt--S-w---T--S-w---t--S-w--wT--S-w--wt--S-w-r-T--S' +
  '-w-r-t--S-w-rwT--S-w-rwt--S-wx--T--S-wx--t--S-wx-wT--S-wx-wt--S-wxr-T--S-wxr-t--S-wxrwT--S-wxrwt' +
  '--Sr----T--Sr----t--Sr---wT--Sr---wt--Sr--r-T--Sr--r-t--Sr--rwT--Sr--rwt--Sr-x--T--Sr-x--t--Sr-x' +
  '-wT--Sr-x-wt--Sr-xr-T--Sr-xr-t--Sr-xrwT--Sr-xrwt--Srw---T--Srw---t--Srw--wT--Srw--wt--Srw-r-T--S' +
  'rw-r-t--Srw-rwT--Srw-rwt--Srwx--T--Srwx--t--Srwx-wT--Srwx-wt--Srwxr-T--Srwxr-t--SrwxrwT--Srwxrwt' +
  '--s-----T--s-----t--s----wT--s----wt--s---r-T--s---r-t--s---rwT--s---rwt--s--x--T--s--x--t--s--x' +
  '-wT--s--x-wt--s--xr-T--s--xr-t--s--xrwT--s--xrwt--s-w---T--s-w---t--s-w--wT--s-w--wt--s-w-r-T--s' +
  '-w-r-t--s-w-rwT--s-w-rwt--s-wx--T--s-wx--t--s-wx-wT--s-wx-wt--s-wxr-T--s-wxr-t--s-wxrwT--s-wxrwt' +
  '--sr----T--sr----t--sr---wT--sr---wt--sr--r-T--sr--r-t--sr--rwT--sr--rwt--sr-x--T--sr-x--t--sr-x' +
  '-wT--sr-x-wt--sr-xr-T--sr-xr-t--sr-xrwT--sr-xrwt--srw---T--srw---t--srw--wT--srw--wt--srw-r-T--s' +
  'rw-r-t--srw-rwT--srw-rwt--srwx--T--srwx--t--srwx-wT--srwx-wt--srwxr-T--srwxr-t--srwxrwT--srwxrwt' +
  '-wS-----T-wS-----t-wS----wT-wS----wt-wS---r-T-wS---r-t-wS---rwT-wS---rwt-wS--x--T-wS--x--t-wS--x' +
  '-wT-wS--x-wt-wS--xr-T-wS--xr-t-wS--xrwT-wS--xrwt-wS-w---T-wS-w---t-wS-w--wT-wS-w--wt-wS-w-r-T-wS' +
  '-w-r-t-wS-w-rwT-wS-w-rwt-wS-wx--T-wS-wx--t-wS-wx-wT-wS-wx-wt-wS-wxr-T-wS-wxr-t-wS-wxrwT-wS-wxrwt' +
  '-wSr----T-wSr----t-wSr---wT-wSr---wt-wSr--r-T-wSr--r-t-wSr--rwT-wSr--rwt-wSr-x--T-wSr-x--t-wSr-x' +
  '-wT-wSr-x-wt-wSr-xr-T-wSr-xr-t-wSr-xrwT-wSr-xrwt-wSrw---T-wSrw---t-wSrw--wT-wSrw--wt-wSrw-r-T-wS' +
  'rw-r-t-wSrw-rwT-wSrw-rwt-wSrwx--T-wSrwx--t-wSrwx-wT-wSrwx-wt-wSrwxr-T-wSrwxr-t-wSrwxrwT-wSrwxrwt' +
  '-ws-----T-ws-----t-ws----wT-ws----wt-ws---r-T-ws---r-t-ws---rwT-ws---rwt-ws--x--T-ws--x--t-ws--x' +
  '-wT-ws--x-wt-ws--xr-T-ws--xr-t-ws--xrwT-ws--xrwt-ws-w---T-ws-w---t-ws-w--wT-ws-w--wt-ws-w-r-T-ws' +
  '-w-r-t-ws-w-rwT-ws-w-rwt-ws-wx--T-ws-wx--t-ws-wx-wT-ws-wx-wt-ws-wxr-T-ws-wxr-t-ws-wxrwT-ws-wxrwt' +
  '-wsr----T-wsr----t-wsr---wT-wsr---wt-wsr--r-T-wsr--r-t-wsr--rwT-wsr--rwt-wsr-x--T-wsr-x--t-wsr-x' +
  '-wT-wsr-x-wt-wsr-xr-T-wsr-xr-t-wsr-xrwT-wsr-xrwt-wsrw---T-wsrw---t-wsrw--wT-wsrw--wt-wsrw-r-T-ws' +
  'rw-r-t-wsrw-rwT-wsrw-rwt-wsrwx--T-wsrwx--t-wsrwx-wT-wsrwx-wt-wsrwxr-T-wsrwxr-t-wsrwxrwT-wsrwxrwt' +
  'r-S-----Tr-S-----tr-S----wTr-S----wtr-S---r-Tr-S---r-tr-S---rwTr-S---rwtr-S--x--Tr-S--x--tr-S--x' +
  '-wTr-S--x-wtr-S--xr-Tr-S--xr-tr-S--xrwTr-S--xrwtr-S-w---Tr-S-w---tr-S-w--wTr-S-w--wtr-S-w-r-Tr-S' +
  '-w-r-tr-S-w-rwTr-S-w-rwtr-S-wx--Tr-S-wx--tr-S-wx-wTr-S-wx-wtr-S-wxr-Tr-S-wxr-tr-S-wxrwTr-S-wxrwt' +
  'r-Sr----Tr-Sr----tr-Sr---wTr-Sr---wtr-Sr--r-Tr-Sr--r-tr-Sr--rwTr-Sr--rwtr-Sr-x--Tr-Sr-x--tr-Sr-x' +
  '-wTr-Sr-x-wtr-Sr-xr-Tr-Sr-xr-tr-Sr-xrwTr-Sr-xrwtr-Srw---Tr-Srw---tr-Srw--wTr-Srw--wtr-Srw-r-Tr-S' +
  'rw-r-tr-Srw-rwTr-Srw-rwtr-Srwx--Tr-Srwx--tr-Srwx-wTr-Srwx-wtr-Srwxr-Tr-Srwxr-tr-SrwxrwTr-Srwxrwt' +
  'r-s-----Tr-s-----tr-s----wTr-s----wtr-s---r-Tr-s---r-tr-s---rwTr-s---rwtr-s--x--Tr-s--x--tr-s--x' +
  '-wTr-s--x-wtr-s--xr-Tr-s--xr-tr-s--xrwTr-s--xrwtr-s-w---Tr-s-w---tr-s-w--wTr-s-w--wtr-s-w-r-Tr-s' +
  '-w-r-tr-s-w-rwTr-s-w-rwtr-s-wx--Tr-s-wx--tr-s-wx-wTr-s-wx-wtr-s-wxr-Tr-s-wxr-tr-s-wxrwTr-s-wxrwt' +
  'r-sr----Tr-sr----tr-sr---wTr-sr---wtr-sr--r-Tr-sr--r-tr-sr--rwTr-sr--rwtr-sr-x--Tr-sr-x--tr-sr-x' +
  '-wTr-sr-x-wtr-sr-xr-Tr-sr-xr-tr-sr-xrwTr-sr-xrwtr-srw---Tr-srw---tr-srw--wTr-srw--wtr-srw-r-Tr-s' +
  'rw-r-tr-srw-rwTr-srw-rwtr-srwx--Tr-srwx--tr-srwx-wTr-srwx-wtr-srwxr-Tr-srwxr-tr-srwxrwTr-srwxrwt' +
  'rwS-----TrwS-----trwS----wTrwS----wtrwS---r-TrwS---r-trwS---rwTrwS---rwtrwS--x--TrwS--x--trwS--x' +
  '-wTrwS--x-wtrwS--xr-TrwS--xr-trwS--xrwTrwS--xrwtrwS-w---TrwS-w---trwS-w--wTrwS-w--wtrwS-w-r-TrwS' +
  '-w-r-trwS-w-rwTrwS-w-rwtrwS-wx--TrwS-wx--trwS-wx-wTrwS-wx-wtrwS-wxr-TrwS-wxr-trwS-wxrwTrwS-wxrwt' +
  'rwSr----TrwSr----trwSr---wTrwSr---wtrwSr--r-TrwSr--r-trwSr--rwTrwSr--rwtrwSr-x--TrwSr-x--trwSr-x' +
  '-wTrwSr-x-wtrwSr-xr-TrwSr-xr-trwSr-xrwTrwSr-xrwtrwSrw---TrwSrw---trwSrw--wTrwSrw--wtrwSrw-r-TrwS' +
  'rw-r-trwSrw-rwTrwSrw-rwtrwSrwx--TrwSrwx--trwSrwx-wTrwSrwx-wtrwSrwxr-TrwSrwxr-trwSrwxrwTrwSrwxrwt' +
  'rws-----Trws-----trws----wTrws----wtrws---r-Trws---r-trws---rwTrws---rwtrws--x--Trws--x--trws--x' +
  '-wTrws--x-wtrws--xr-Trws--xr-trws--xrwTrws--xrwtrws-w---Trws-w---trws-w--wTrws-w--wtrws-w-r-Trws' +
  '-w-r-trws-w-rwTrws-w-rwtrws-wx--Trws-wx--trws-wx-wTrws-wx-wtrws-wxr-Trws-wxr-trws-wxrwTrws-wxrwt' +
  'rwsr----Trwsr----trwsr---wTrwsr---wtrwsr--r-Trwsr--r-trwsr--rwTrwsr--rwtrwsr-x--Trwsr-x--trwsr-x' +
  '-wTrwsr-x-wtrwsr-xr-Trwsr-xr-trwsr-xrwTrwsr-xrwtrwsrw---Trwsrw---trwsrw--wTrwsrw--wtrwsrw-r-Trws' +
  'rw-r-trwsrw-rwTrwsrw-rwtrwsrwx--Trwsrwx--trwsrwx-wTrwsrwx-wtrwsrwxr-Trwsrwxr-trwsrwxrwTrwsrwxrwt' +
  '--S--S-----S--S--x--S--S-w---S--S-wx--S--Sr----S--Sr-x--S--Srw---S--Srwx--S--s-----S--s--x--S--s' +
  '-w---S--s-wx--S--sr----S--sr-x--S--srw---S--srwx--S-wS-----S-wS--x--S-wS-w---S-wS-wx--S-wSr----S' +
  '-wSr-x--S-wSrw---S-wSrwx--S-ws-----S-ws--x--S-ws-w---S-ws-wx--S-wsr----S-wsr-x--S-wsrw---S-wsrwx' +
  '--Sr-S-----Sr-S--x--Sr-S-w---Sr-S-wx--Sr-Sr----Sr-Sr-x--Sr-Srw---Sr-Srwx--Sr-s-----Sr-s--x--Sr-s' +
  '-w---Sr-s-wx--Sr-sr----Sr-sr-x--Sr-srw---Sr-srwx--SrwS-----SrwS--x--SrwS-w---SrwS-wx--SrwSr----S' +
  'rwSr-x--SrwSrw---SrwSrwx--Srws-----Srws--x--Srws-w---Srws-wx--Srwsr----Srwsr-x--Srwsrw---Srwsrwx' +
  '--s--S-----s--S--x--s--S-w---s--S-wx--s--Sr----s--Sr-x--s--Srw---s--Srwx--s--s-----s--s--x--s--s' +
  '-w---s--s-wx--s--sr----s--sr-x--s--srw---s--srwx--s-wS-----s-wS--x--s-wS-w---s-wS-wx--s-wSr----s' +
  '-wSr-x--s-wSrw---s-wSrwx--s-ws-----s-ws--x--s-ws-w---s-ws-wx--s-wsr----s-wsr-x--s-wsrw---s-wsrwx' +
  '--sr-S-----sr-S--x--sr-S-w---sr-S-wx--sr-Sr----sr-Sr-x--sr-Srw---sr-Srwx--sr-s-----sr-s--x--sr-s' +
  '-w---sr-s-wx--sr-sr----sr-sr-x--sr-srw---sr-srwx--srwS-----srwS--x--srwS-w---srwS-wx--srwSr----s' +
  'rwSr-x--srwSrw---srwSrwx--srws-----srws--x--srws-w---srws-wx--srwsr----srwsr-x--srwsrw---srwsrwx' +
  '-wS--S----wS--S--x-wS--S-w--wS--S-wx-wS--Sr---wS--Sr-x-wS--Srw--wS--Srwx-wS--s----wS--s--x-wS--s' +
  '-w--wS--s-wx-wS--sr---wS--sr-x-wS--srw--wS--srwx-wS-wS----wS-wS--x-wS-wS-w--wS-wS-wx-wS-wSr---wS' +
  '-wSr-x-wS-wSrw--wS-wSrwx-wS-ws----wS-ws--x-wS-ws-w--wS-ws-wx-wS-wsr---wS-wsr-x-wS-wsrw--wS-wsrwx' +
  '-wSr-S----wSr-S--x-wSr-S-w--wSr-S-wx-wSr-Sr---wSr-Sr-x-wSr-Srw--wSr-Srwx-wSr-s----wSr-s--x-wSr-s' +
  '-w--wSr-s-wx-wSr-sr---wSr-sr-x-wSr-srw--wSr-srwx-wSrwS----wSrwS--x-wSrwS-w--wSrwS-wx-wSrwSr---wS' +
  'rwSr-x-wSrwSrw--wSrwSrwx-wSrws----wSrws--x-wSrws-w--wSrws-wx-wSrwsr---wSrwsr-x-wSrwsrw--wSrwsrwx' +
  '-ws--S----ws--S--x-ws--S-w--ws--S-wx-ws--Sr---ws--Sr-x-ws--Srw--ws--Srwx-ws--s----ws--s--x-ws--s' +
  '-w--ws--s-wx-ws--sr---ws--sr-x-ws--srw--ws--srwx-ws-wS----ws-wS--x-ws-wS-w--ws-wS-wx-ws-wSr---ws' +
  '-wSr-x-ws-wSrw--ws-wSrwx-ws-ws----ws-ws--x-ws-ws-w--ws-ws-wx-ws-wsr---ws-wsr-x-ws-wsrw--ws-wsrwx' +
  '-wsr-S----wsr-S--x-wsr-S-w--wsr-S-wx-wsr-Sr---wsr-Sr-x-wsr-Srw--wsr-Srwx-wsr-s----wsr-s--x-wsr-s' +
  '-w--wsr-s-wx-wsr-sr---wsr-sr-x-wsr-srw--wsr-srwx-wsrwS----wsrwS--x-wsrwS-w--wsrwS-wx-wsrwSr---ws' +
  'rwSr-x-wsrwSrw--wsrwSrwx-wsrws----wsrws--x-wsrws-w--wsrws-wx-wsrwsr---wsrwsr-x-wsrwsrw--wsrwsrwx' +
  'r-S--S---r-S--S--xr-S--S-w-r-S--S-wxr-S--Sr--r-S--Sr-xr-S--Srw-r-S--Srwxr-S--s---r-S--s--xr-S--s' +
  '-w-r-S--s-wxr-S--sr--r-S--sr-xr-S--srw-r-S--srwxr-S-wS---r-S-wS--xr-S-wS-w-r-S-wS-wxr-S-wSr--r-S' +
  '-wSr-xr-S-wSrw-r-S-wSrwxr-S-ws---r-S-ws--xr-S-ws-w-r-S-ws-wxr-S-wsr--r-S-wsr-xr-S-wsrw-r-S-wsrwx' +
  'r-Sr-S---r-Sr-S--xr-Sr-S-w-r-Sr-S-wxr-Sr-Sr--r-Sr-Sr-xr-Sr-Srw-r-Sr-Srwxr-Sr-s---r-Sr-s--xr-Sr-s' +
  '-w-r-Sr-s-wxr-Sr-sr--r-Sr-sr-xr-Sr-srw-r-Sr-srwxr-SrwS---r-SrwS--xr-SrwS-w-r-SrwS-wxr-SrwSr--r-S' +
  'rwSr-xr-SrwSrw-r-SrwSrwxr-Srws---r-Srws--xr-Srws-w-r-Srws-wxr-Srwsr--r-Srwsr-xr-Srwsrw-r-Srwsrwx' +
  'r-s--S---r-s--S--xr-s--S-w-r-s--S-wxr-s--Sr--r-s--Sr-xr-s--Srw-r-s--Srwxr-s--s---r-s--s--xr-s--s' +
  '-w-r-s--s-wxr-s--sr--r-s--sr-xr-s--srw-r-s--srwxr-s-wS---r-s-wS--xr-s-wS-w-r-s-wS-wxr-s-wSr--r-s' +
  '-wSr-xr-s-wSrw-r-s-wSrwxr-s-ws---r-s-ws--xr-s-ws-w-r-s-ws-wxr-s-wsr--r-s-wsr-xr-s-wsrw-r-s-wsrwx' +
  'r-sr-S---r-sr-S--xr-sr-S-w-r-sr-S-wxr-sr-Sr--r-sr-Sr-xr-sr-Srw-r-sr-Srwxr-sr-s---r-sr-s--xr-sr-s' +
  '-w-r-sr-s-wxr-sr-sr--r-sr-sr-xr-sr-srw-r-sr-srwxr-srwS---r-srwS--xr-srwS-w-r-srwS-wxr-srwSr--r-s' +
  'rwSr-xr-srwSrw-r-srwSrwxr-srws---r-srws--xr-srws-w-r-srws-wxr-srwsr--r-srwsr-xr-srwsrw-r-srwsrwx' +
  'rwS--S---rwS--S--xrwS--S-w-rwS--S-wxrwS--Sr--rwS--Sr-xrwS--Srw-rwS--SrwxrwS--s---rwS--s--xrwS--s' +
  '-w-rwS--s-wxrwS--sr--rwS--sr-xrwS--srw-rwS--srwxrwS-wS---rwS-wS--xrwS-wS-w-rwS-wS-wxrwS-wSr--rwS' +
  '-wSr-xrwS-wSrw-rwS-wSrwxrwS-ws---rwS-ws--xrwS-ws-w-rwS-ws-wxrwS-wsr--rwS-wsr-xrwS-wsrw-rwS-wsrwx' +
  'rwSr-S---rwSr-S--xrwSr-S-w-rwSr-S-wxrwSr-Sr--rwSr-Sr-xrwSr-Srw-rwSr-SrwxrwSr-s---rwSr-s--xrwSr-s' +
  '-w-rwSr-s-wxrwSr-sr--rwSr-sr-xrwSr-srw-rwSr-srwxrwSrwS---rwSrwS--xrwSrwS-w-rwSrwS-wxrwSrwSr--rwS' +
  'rwSr-xrwSrwSrw-rwSrwSrwxrwSrws---rwSrws--xrwSrws-w-rwSrws-wxrwSrwsr--rwSrwsr-xrwSrwsrw-rwSrwsrwx' +
  'rws--S---rws--S--xrws--S-w-rws--S-wxrws--Sr--rws--Sr-xrws--Srw-rws--Srwxrws--s---rws--s--xrws--s' +
  '-w-rws--s-wxrws--sr--rws--sr-xrws--srw-rws--srwxrws-wS---rws-wS--xrws-wS-w-rws-wS-wxrws-wSr--rws' +
  '-wSr-xrws-wSrw-rws-wSrwxrws-ws---rws-ws--xrws-ws-w-rws-ws-wxrws-wsr--rws-wsr-xrws-wsrw-rws-wsrwx' +
  'rwsr-S---rwsr-S--xrwsr-S-w-rwsr-S-wxrwsr-Sr--rwsr-Sr-xrwsr-Srw-rwsr-Srwxrwsr-s---rwsr-s--xrwsr-s' +
  '-w-rwsr-s-wxrwsr-sr--rwsr-sr-xrwsr-srw-rwsr-srwxrwsrwS---rwsrwS--xrwsrwS-w-rwsrwS-wxrwsrwSr--rws' +
  'rwSr-xrwsrwSrw-rwsrwSrwxrwsrws---rwsrws--xrwsrws-w-rwsrws-wxrwsrwsr--rwsrwsr-xrwsrwsrw-rwsrwsrwx' +
  '--S--S--T--S--S--t--S--S-wT--S--S-wt--S--Sr-T--S--Sr-t--S--SrwT--S--Srwt--S--s--T--S--s--t--S--s' +
  '-wT--S--s-wt--S--sr-T--S--sr-t--S--srwT--S--srwt--S-wS--T--S-wS--t--S-wS-wT--S-wS-wt--S-wSr-T--S' +
  '-wSr-t--S-wSrwT--S-wSrwt--S-ws--T--S-ws--t--S-ws-wT--S-ws-wt--S-wsr-T--S-wsr-t--S-wsrwT--S-wsrwt' +
  '--Sr-S--T--Sr-S--t--Sr-S-wT--Sr-S-wt--Sr-Sr-T--Sr-Sr-t--Sr-SrwT--Sr-Srwt--Sr-s--T--Sr-s--t--Sr-s' +
  '-wT--Sr-s-wt--Sr-sr-T--Sr-sr-t--Sr-srwT--Sr-srwt--SrwS--T--SrwS--t--SrwS-wT--SrwS-wt--SrwSr-T--S' +
  'rwSr-t--SrwSrwT--SrwSrwt--Srws--T--Srws--t--Srws-wT--Srws-wt--Srwsr-T--Srwsr-t--SrwsrwT--Srwsrwt' +
  '--s--S--T--s--S--t--s--S-wT--s--S-wt--s--Sr-T--s--Sr-t--s--SrwT--s--Srwt--s--s--T--s--s--t--s--s' +
  '-wT--s--s-wt--s--sr-T--s--sr-t--s--srwT--s--srwt--s-wS--T--s-wS--t--s-wS-wT--s-wS-wt--s-wSr-T--s' +
  '-wSr-t--s-wSrwT--s-wSrwt--s-ws--T--s-ws--t--s-ws-wT--s-ws-wt--s-wsr-T--s-wsr-t--s-wsrwT--s-wsrwt' +
  '--sr-S--T--sr-S--t--sr-S-wT--sr-S-wt--sr-Sr-T--sr-Sr-t--sr-SrwT--sr-Srwt--sr-s--T--sr-s--t--sr-s' +
  '-wT--sr-s-wt--sr-sr-T--sr-sr-t--sr-srwT--sr-srwt--srwS--T--srwS--t--srwS-wT--srwS-wt--srwSr-T--s' +
  'rwSr-t--srwSrwT--srwSrwt--srws--T--srws--t--srws-wT--srws-wt--srwsr-T--srwsr-t--srwsrwT--srwsrwt' +
  '-wS--S--T-wS--S--t-wS--S-wT-wS--S-wt-wS--Sr-T-wS--Sr-t-wS--SrwT-wS--Srwt-wS--s--T-wS--s--t-wS--s' +
  '-wT-wS--s-wt-wS--sr-T-wS--sr-t-wS--srwT-wS--srwt-wS-wS--T-wS-wS--t-wS-wS-wT-wS-wS-wt-wS-wSr-T-wS' +
  '-wSr-t-wS-wSrwT-wS-wSrwt-wS-ws--T-wS-ws--t-wS-ws-wT-wS-ws-wt-wS-wsr-T-wS-wsr-t-wS-wsrwT-wS-wsrwt' +
  '-wSr-S--T-wSr-S--t-wSr-S-wT-wSr-S-wt-wSr-Sr-T-wSr-Sr-t-wSr-SrwT-wSr-Srwt-wSr-s--T-wSr-s--t-wSr-s' +
  '-wT-wSr-s-wt-wSr-sr-T-wSr-sr-t-wSr-srwT-wSr-srwt-wSrwS--T-wSrwS--t-wSrwS-wT-wSrwS-wt-wSrwSr-T-wS' +
  'rwSr-t-wSrwSrwT-wSrwSrwt-wSrws--T-wSrws--t-wSrws-wT-wSrws-wt-wSrwsr-T-wSrwsr-t-wSrwsrwT-wSrwsrwt' +
  '-ws--S--T-ws--S--t-ws--S-wT-ws--S-wt-ws--Sr-T-ws--Sr-t-ws--SrwT-ws--Srwt-ws--s--T-ws--s--t-ws--s' +
  '-wT-ws--s-wt-ws--sr-T-ws--sr-t-ws--srwT-ws--srwt-ws-wS--T-ws-wS--t-ws-wS-wT-ws-wS-wt-ws-wSr-T-ws' +
  '-wSr-t-ws-wSrwT-ws-wSrwt-ws-ws--T-ws-ws--t-ws-ws-wT-ws-ws-wt-ws-wsr-T-ws-wsr-t-ws-wsrwT-ws-wsrwt' +
  '-wsr-S--T-wsr-S--t-wsr-S-wT-wsr-S-wt-wsr-Sr-T-wsr-Sr-t-wsr-SrwT-wsr-Srwt-wsr-s--T-wsr-s--t-wsr-s' +
  '-wT-wsr-s-wt-wsr-sr-T-wsr-sr-t-wsr-srwT-wsr-srwt-wsrwS--T-wsrwS--t-wsrwS-wT-wsrwS-wt-wsrwSr-T-ws' +
  'rwSr-t-wsrwSrwT-wsrwSrwt-wsrws--T-wsrws--t-wsrws-wT-wsrws-wt-wsrwsr-T-wsrwsr-t-wsrwsrwT-wsrwsrwt' +
  'r-S--S--Tr-S--S--tr-S--S-wTr-S--S-wtr-S--Sr-Tr-S--Sr-tr-S--SrwTr-S--Srwtr-S--s--Tr-S--s--tr-S--s' +
  '-wTr-S--s-wtr-S--sr-Tr-S--sr-tr-S--srwTr-S--srwtr-S-wS--Tr-S-wS--tr-S-wS-wTr-S-wS-wtr-S-wSr-Tr-S' +
  '-wSr-tr-S-wSrwTr-S-wSrwtr-S-ws--Tr-S-ws--tr-S-ws-wTr-S-ws-wtr-S-wsr-Tr-S-wsr-tr-S-wsrwTr-S-wsrwt' +
  'r-Sr-S--Tr-Sr-S--tr-Sr-S-wTr-Sr-S-wtr-Sr-Sr-Tr-Sr-Sr-tr-Sr-SrwTr-Sr-Srwtr-Sr-s--Tr-Sr-s--tr-Sr-s' +
  '-wTr-Sr-s-wtr-Sr-sr-Tr-Sr-sr-tr-Sr-srwTr-Sr-srwtr-SrwS--Tr-SrwS--tr-SrwS-wTr-SrwS-wtr-SrwSr-Tr-S' +
  'rwSr-tr-SrwSrwTr-SrwSrwtr-Srws--Tr-Srws--tr-Srws-wTr-Srws-wtr-Srwsr-Tr-Srwsr-tr-SrwsrwTr-Srwsrwt' +
  'r-s--S--Tr-s--S--tr-s--S-wTr-s--S-wtr-s--Sr-Tr-s--Sr-tr-s--SrwTr-s--Srwtr-s--s--Tr-s--s--tr-s--s' +
  '-wTr-s--s-wtr-s--sr-Tr-s--sr-tr-s--srwTr-s--srwtr-s-wS--Tr-s-wS--tr-s-wS-wTr-s-wS-wtr-s-wSr-Tr-s' +
  '-wSr-tr-s-wSrwTr-s-wSrwtr-s-ws--Tr-s-ws--tr-s-ws-wTr-s-ws-wtr-s-wsr-Tr-s-wsr-tr-s-wsrwTr-s-wsrwt' +
  'r-sr-S--Tr-sr-S--tr-sr-S-wTr-sr-S-wtr-sr-Sr-Tr-sr-Sr-tr-sr-SrwTr-sr-Srwtr-sr-s--Tr-sr-s--tr-sr-s' +
  '-wTr-sr-s-wtr-sr-sr-Tr-sr-sr-tr-sr-srwTr-sr-srwtr-srwS--Tr-srwS--tr-srwS-wTr-srwS-wtr-srwSr-Tr-s' +
  'rwSr-tr-srwSrwTr-srwSrwtr-srws--Tr-srws--tr-srws-wTr-srws-wtr-srwsr-Tr-srwsr-tr-srwsrwTr-srwsrwt' +
  'rwS--S--TrwS--S--trwS--S-wTrwS--S-wtrwS--Sr-TrwS--Sr-trwS--SrwTrwS--SrwtrwS--s--TrwS--s--trwS--s' +
  '-wTrwS--s-wtrwS--sr-TrwS--sr-trwS--srwTrwS--srwtrwS-wS--TrwS-wS--trwS-wS-wTrwS-wS-wtrwS-wSr-TrwS' +
  '-wSr-trwS-wSrwTrwS-wSrwtrwS-ws--TrwS-ws--trwS-ws-wTrwS-ws-wtrwS-wsr-TrwS-wsr-trwS-wsrwTrwS-wsrwt' +
  'rwSr-S--TrwSr-S--trwSr-S-wTrwSr-S-wtrwSr-Sr-TrwSr-Sr-trwSr-SrwTrwSr-SrwtrwSr-s--TrwSr-s--trwSr-s' +
  '-wTrwSr-s-wtrwSr-sr-TrwSr-sr-trwSr-srwTrwSr-srwtrwSrwS--TrwSrwS--trwSrwS-wTrwSrwS-wtrwSrwSr-TrwS' +
  'rwSr-trwSrwSrwTrwSrwSrwtrwSrws--TrwSrws--trwSrws-wTrwSrws-wtrwSrwsr-TrwSrwsr-trwSrwsrwTrwSrwsrwt' +
  'rws--S--Trws--S--trws--S-wTrws--S-wtrws--Sr-Trws--Sr-trws--SrwTrws--Srwtrws--s--Trws--s--trws--s' +
  '-wTrws--s-wtrws--sr-Trws--sr-trws--srwTrws--srwtrws-wS--Trws-wS--trws-wS-wTrws-wS-wtrws-wSr-Trws' +
  '-wSr-trws-wSrwTrws-wSrwtrws-ws--Trws-ws--trws-ws-wTrws-ws-wtrws-wsr-Trws-wsr-trws-wsrwTrws-wsrwt' +
  'rwsr-S--Trwsr-S--trwsr-S-wTrwsr-S-wtrwsr-Sr-Trwsr-Sr-trwsr-SrwTrwsr-Srwtrwsr-s--Trwsr-s--trwsr-s' +
  '-wTrwsr-s-wtrwsr-sr-Trwsr-sr-trwsr-srwTrwsr-srwtrwsrwS--TrwsrwS--trwsrwS-wTrwsrwS-wtrwsrwSr-Trws' +
  'rwSr-trwsrwSrwTrwsrwSrwtrwsrws--Trwsrws--trwsrws-wTrwsrws-wtrwsrwsr-Trwsrwsr-trwsrwsrwTrwsrwsrwt';

/** 0000-7777 의 심볼릭 표기. 범위를 벗어나면 던진다 — 테스트에서만 쓰므로 안전하다. */
export function symbolicForMode(mode: number): string {
  if (!Number.isInteger(mode) || mode < 0 || mode > 0o7777) {
    throw new Error(`표에 없는 모드: ${mode}`);
  }
  return TABLE.slice(mode * 9, mode * 9 + 9);
}

/** 표 전체를 훑는 테스트용 */
export const ALL_MODES: readonly number[] = Array.from({ length: 4096 }, (_, i) => i);
